@startditaa()

    The difference between the Front and Back end and
    the Client and Server side of an application.
 
              +------------------+ +--------------+
              |Delivery Mechanism| |System Boundry|
              +-----------------=+ +-------------=+
                                 : :
*--------------------------------:-:-------------------*
                                 : :
                                 : :
+-----------------------------+  : :  +--------------+
|          Front End          | ----> |   Back End   |
+-----------------------------+  : :  +--------------+
                  : :            : :
                  : :            : :
+----+       +----+-+---------+  : :  +--------------+
| UI | ----> |     Logic      | ----> |  Application |
+----+       +----+-+---------+  : :  +--------------+
                  : :            : :
+--------------+  : :  +-----------------------------+
|    Browser   | ----> |            Server           |
+--------------+  : :  +-----------------------------+
                  : :
                  : :
*-----------------:-:----------------------------------*
                  : :
   +--------------+ +------+-------+
   |Browser Boundy| |Server Boundry|
   +-------------=+ +-------------=+

@endditaa
